<?php echo $this->form->renderForm(false); ?>

<style type="text/css">
    button:hover {
        color:#FFF !important;
    }
    
    #tblHistorico td, #tblHistorico th {
        text-align: center;
        vertical-align: middle;
    }
    
    
</style>

<div class="col-md-12">
    <h2 align="center">Emitir Ficha</h2>

    <table class="table general table-bordered table-condensed" style="width:40%">
        <caption>DATOS BÚSQUEDA</caption>
        <tbody>
            <tr>
                <th style="text-align:center;width:40%;vertical-align:middle;">
                    <?php echo $this->form->getElement(Application_Form_SolicitarFicha::E_FICHA)->getLabel(); ?>
                </th>
                <td>
                    <?php 
                        echo $this->form->getElement(Application_Form_SolicitarFicha::E_FICHA)->renderViewHelper(),
                             $this->form->getElement(Application_Form_SolicitarFicha::E_FICHA)->getDescription(),
                             $this->form->getElement(Application_Form_SolicitarFicha::E_FICHA)->renderErrors();
                    ?>
                </td>
            </tr>
        </tbody>
    </table>

    <p align="center">
        <?php 
            echo $this->form->getElement(Application_Form_SolicitarFicha::E_BUSCAR)->renderViewHelper(),
                 $this->form->getElement(Application_Form_SolicitarFicha::E_NUEVABUS)->renderViewHelper();
        ?>
    </p>

    <?php
        if ($this->trabajador):
    ?>
            <table class="table general table-bordered table-condensed" summary="Datos Ficha" style="width:80%;">
                <caption>DATOS DEL TRABAJADOR</caption>
                <tbody>  
                    <tr>
                        <th style="width:90px;">Ficha:</th>
                        <td><?php echo $this->trabajador->ficha; ?> </td>

                        <th style="width:90px;">Gerencia:</th>
                        <td><?php if(!empty($this->trabajador->organigrama[2])){ echo $this->trabajador->organigrama[2]->centro_costo; }else{ echo $this->trabajador->organigrama[1]->centro_costo; } ?> </td>

                        <th style="width:115px;">Fecha Ingreso:</th>
                        <td class="text-center">
                            <?php echo Fmo_Util::stringToZendDate($this->trabajador->fecha_ingreso)->get('dd/MM/yyyy'); ?>
                        </td>
                    </tr>
                    <tr>
                        <th style="width:55px;">Cédula:</th>
                        <td><?php echo $this->trabajador->cedula; ?> </td>

                        <th>Cargo:</th>
                        <td>
                            <?php 
                                //if(!empty($this->trabajador->organigrama[2])){ echo $this->trabajador->organigrama[1]->centro_costo; }else{ echo $this->trabajador->organigrama[0]->centro_costo; };
                                echo $this->trabajador->{Fmo_Model_Personal::CARGO};
                            ?>
                        </td>

                        <th rowspan="2" style="vertical-align:middle;">
                            Actividad:
                        </th>
                        <td rowspan="2" style="vertical-align:middle;text-align:center;">
                            <?php  echo $this->trabajador->actividad; ?>
                        </td>
                    </tr>
                    <tr>
                        <th>Nombre:</th>
                        <td><?php echo $this->trabajador->apellido, " ", $this->trabajador->nombre; ?> </td>

                        <th>Nómina:</th>
                        <td><?php echo $this->trabajador->nomina; ?> </td>
                    </tr>
                </tbody>  
            </table>
            <br>

            <?php
                if ($this->trabajador && !Application_Model_FichaTrabajador::fichaActiva($this->trabajador->cedula) && $this->valido):
            ?>
                    <table class="table general table-bordered table-condensed" style="width:40%;">
                        <caption>DATOS NUEVA FICHA</caption>
                        <tbody>
                            <tr>
                                <th style="text-align:center;width:40%;vertical-align:middle;">
                                    <?php 
                                        echo $this->form->getElement(Application_Form_SolicitarFicha::E_CODTARJETA)->getLabel();
                                    ?>
                                </th>
                                <td>
                                    <?php 
                                        echo $this->form->getElement(Application_Form_SolicitarFicha::E_CODTARJETA)->renderViewHelper(),
                                             $this->form->getElement(Application_Form_SolicitarFicha::E_CODTARJETA)->getDescription(),
                                             $this->form->getElement(Application_Form_SolicitarFicha::E_CODTARJETA)->renderErrors();
                                    ?>
                                </td>
                            </tr>
                        </tbody>
                    </table>

                    <p align="center">
                        <?php
                            echo $this->form->getElement(Application_Form_SolicitarFicha::E_EMITIR)->renderViewHelper();
                        ?>
                    </p>

            <?php endif; ?>

            <table id="tblHistorico" class="table general table-bordered table-condensed" summary="Histórico Fichas">
                <caption>HISTÓRICO DE FICHAS</caption>
                <thead>
                    <tr>
                        <th style="width:10%;">Cod. Tarjeta</th>
                        <th style="width:10%;">Motivo</th>
                        <th style="width:6%;">Activa</th>
                        <th style="width:8%;">Fecha Emisión</th>
                        <th style="width:20%;">Emitida por</th>
                        <th style="width:8%;">Fecha Anulación</th>
                        <th style="width:20%;">Anulada por</th>
                        <th style="width:10%;">Acción</th>
                    </tr>
                </thead>
                <tbody>  
                    <?php
                        if ($this->hist_fichas):
                            foreach ($this->hist_fichas as $row):
                    ?>
                                <tr>
                                    <td>
                                        <?php echo $row->cod_ficha; ?>
                                    </td>
                                    <td>
                                        <?php 
                                            echo $row->motivo; 
                                        ?>
                                    </td>
                                    <td>
                                        <?php echo $row->activa ? $this->img('ico_bien.png') : $this->img('ico_mal.png'); ?>
                                    </td>
                                    <td>
                                        <?php
                                            echo Fmo_Util::stringToZendDate($row->fecha_crea)->get('dd/MM/yyyy'), '<br>',
                                                 Fmo_Util::stringToZendDate($row->fecha_crea)->get('hh:mma')
                                        ?>
                                    </td>
                                    <td>
                                        <?php
                                            echo $row->usu_crea ? $row->nombre_usu_crea . '<br><b>FMO-' . $row->ficha_usu_crea . '</b> ' : '-';
                                        ?>
                                    </td>
                                    <td>
                                        <?php
                                            echo $row->fecha_mod ? Fmo_Util::stringToZendDate($row->fecha_mod)->get('dd/MM/yyyy') . '<br>'.
                                                 Fmo_Util::stringToZendDate($row->fecha_mod)->get('hh:mma') : '-';
                                        ?>
                                    </td>
                                    <td>
                                        <?php
                                            echo $row->usu_mod ? $row->nombre_usu_mod . '<br><b>FMO-' . $row->ficha_usu_mod . '</b> ' : '-';
                                        ?>
                                    </td>
                                    <td>
                                        <?php
                                            if ($row->activa):
                                        ?>
                                                <a href="<?php echo $this->url(array('controller' => 'ficha', 'action' => 'inactivar', 'id' => $row->id)); ?>" title="Inactivar"><?php echo $this->img('ico_cancelar.png'); ?></a>
                                        <?php   
                                            endif;
                                        ?>
                                    </td>
                                </tr>                
                    <?php
                            endforeach;
                        else:
                    ?>
                            <tr>
                                <td colspan="8" class="text-center">
                                    <i>El trabajador no tiene ficha emitida.</i>
                                </td>
                            </tr>
                    <?php
                        endif;
                    ?>
                </tbody>
            </table>
            <br>
    <?php
        endif;
    ?>

</div>