<table class="general" summary="Detalle de Variable de Configuración"> 
<caption>DETALLE DE LA VARIABLE DE CONFIGURACIÓN</caption>
<tr>
    <th width="15%" align="right">Código:</th>
    <td><?php echo $this->escape($this->variable->id); ?></td>
</tr><tr>
    <th align="right">Nombre:</th>
    <td><?php echo $this->escape($this->variable->nombre); ?></td>
</tr><tr>
    <th align="right">Valor:</th>
    <td><?php 
switch ($this->variable->tipo_dato):
    case Application_Model_DbTable_Configuracion::T_BOOLEAN:
        echo $this->escape(Application_Form_Configuracion::$booleanOptions[$this->variable->valor]);
        break;
    case Application_Model_DbTable_Configuracion::T_DATE:
        echo $this->escape(Fmo_Util::stringToZendDate($this->variable->valor)->toString(Zend_Date::DATES));
        break;
    case Application_Model_DbTable_Configuracion::T_TIMESTAMP_WITHOUT_TIME_ZONE:
        echo $this->escape(Fmo_Util::stringToZendDate($this->variable->valor)->toString(Zend_Date::DATETIME));
        break;            
    case Application_Model_DbTable_Configuracion::T_TIME_WITHOUT_TIME_ZONE:
        echo $this->escape(Fmo_Util::stringToZendDate($this->variable->valor, 'HH:mm:ss ZZZZ')->toString(Zend_Date::TIMES));
        break;                        
    case Application_Model_DbTable_Configuracion::T_FLOAT:
    case Application_Model_DbTable_Configuracion::T_INTEGER:
    case Application_Model_DbTable_Configuracion::T_NUMERIC:
    case Application_Model_DbTable_Configuracion::T_SMALLINT:
        echo $this->escape(Zend_Locale_Format::toNumber($this->variable->valor));
        break;
    case Application_Model_DbTable_Configuracion::T_INTERVAL:
        echo $this->escape(Fmo_Util::translateAgeEnglighToSpanish($this->variable->valor));
        break;
    case Application_Model_DbTable_Configuracion::T_LIST:
        $listRow = $this->variable->findParentRow('Application_Model_DbTable_ConfiguracionLista');
        if ($listRow instanceof Zend_Db_Table_Row_Abstract):
            echo $this->escape($listRow->nombre);
            break;
        endif;                
    default:
        echo $this->escape($this->variable->valor);
        break;
endswitch; ?></td>
</tr>
</table>
<p align="center">
    <a class="button" href="<?php echo $this->baseUrl($this->urlDefault); ?>"><?php echo $this->img('ico_volver.png'); ?> Volver</a>
</p>