<style type="text/css">
    button:hover {
        color:#FFF !important;
    }

    #tblErrores caption, #tblResultado caption {
	font-weight: bold;
	font-size: medium;
	vertical-align: middle;
	padding-top: 10px;
	padding-bottom: 3px;
        color: #777;
        text-align: left;
    }

    .buttons-excel, #tblErrores_length {
        margin-top: 5px;
    }
</style>

<div class="container-fluid" align="center">
    <div class="row" style="width:80%;">
        <center>
            <h3>RESULTADO CARGA MASIVA </h3>
        </center>

        <table id="tblResultado" class="table general table-bordered table-condensed">
            <caption>REGISTROS PROCESADOS</caption>
            <tbody>
                <tr>
                    <th class="text-center" style="width:20%;">
                        Trabajadores Procesados:
                    </th>
                    <td style="text-align:center;width:14%;">
                        <?php echo $this->total; ?>
                    </td>
                    <th class="text-center" style="width:20%;">
                        Procesados Correctamente:
                    </th>
                    <td style="text-align:center;width:13%;">
                        <?php echo $this->correctos; ?>
                    </td>
                    <th class="text-center" style="width:20%;">
                        Errores:
                    </th>
                    <td style="text-align:center;width:13%;">
                        <?php echo $this->errados; ?>
                    </td>
                </tr>
            </tbody>
        </table>

        <br>

        <?php
            if ($this->errores !== null):
        ?>
                <table id="tblErrores" class="table general table-striped table-bordered table-condensed table-hover">
                    <caption>ERRORES DEL PROCESO</caption>
                    <thead>
                        <tr>
                            <th style="text-align:center;width:15%;">NRO REGISTRO</th>
                            <th style="text-align:center;width:10%;">FICHA</th>
                            <th style="text-align:center;width:75%;">ERROR</th>
                        </tr>
                    </thead>
                    <tbody>
                <?php
                    foreach ($this->errores as $error):
                ?>
                        <tr>
                            <td style="text-align:center;">
                                <?php echo $error['registro']; ?>
                            </td>
                            <td style="text-align:center;">
                                <?php echo $error['ficha']; ?>
                            </td>
                            <td>
                                <?php echo $error['error']; ?>
                            </td>
                        </tr>
                <?php
                    endforeach;
                ?>
                    </tbody>
                </table>
        <?php
            endif;
        ?>

        <p align="center">
            <a class="btn btn-default" href="<?php echo $this->url(array('controller' => 'autorizado', 'action' => 'cargamasiva')); ?>">
                Volver
            </a>
        </p>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('#tblErrores').DataTable({
            dom: "<'row' t><'row'<'col-sm-4'l><'col-sm-offset-6 col-sm-2 text-right'Br>><'row' p>",
            paging:   true,
            pageLength: 10,
            buttons: [
                { 
                    extend: 'excelHtml5', 
                    footer: true,
                    text: 'Exportar a Calc',
                },
            ],
            columnDefs: [
                {
                    orderable: false,
                    searchable: false,
                    targets: [0,1,2]
                },
            ],
            order: [],
            language: {
                emptyTable: 'La consulta no devolvió registros.',
            },
            fnDrawCallback: function() {
                if (Math.ceil((this.fnSettings().fnRecordsDisplay()) / this.fnSettings()._iDisplayLength) > 1) {
                    $('.dataTables_paginate').css('display', 'block');
                } else {
                    $('.dataTables_paginate').css('display', 'none');
                }
            }
        });
    });
</script>